version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile   # React Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile  # rename backend Dockerfile
    container_name: spring-backend
    ports:
      - "8089:8089"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
